### ISSUE TITLE
Convert external taxonomy to standardised format

### ISSUE THREAD

**Issue by sujaikumar** [tolkit/tolkein#4]
eg: NCBI taxonomy is in taxdump files
Catalogue of Life is in some other format.
We want to be able to standardise and write to multiple output formats (perhaps to ncbi nodes.dmp names.dmp)

**Comment by rjchallis** [comment]
working on adding NCBI parser in a generic way that should be able to support multiple output formats and allow other parsers to be plugged in.

will look like:

```
def parse_ncbi_taxdump(path, root):
    # do parsing
    for lineage in taxonomy:
        yield "taxon_id-%s" % taxon_id, lineage

def parse_taxonomy(type, path, root=None):
    parsers = {"ncbi": parse_ncbi_taxdump}
    parser = parsers.get(type.lower(), None)
    return parser(path, root)
```

**Comment by rjchallis** [comment]
Should the JSON format include `depth` in each `lineage` entry? This information is already implicit in the list index, but exposing it would allow for querying taxa at specific levels from a root taxon ID in [genomehubs](https://github.com/genomehubs/genomehubs). Alternatively this could be added during indexing to avoid making the default data structure any larger.
